// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwO7Q-Ej0HFOFWtlOXYibaIS4FcFDl5zA',
    appId: '1:361709866355:web:4c55a4c5f251e5229e4906',
    messagingSenderId: '361709866355',
    projectId: 'note-app-f7203',
    authDomain: 'note-app-f7203.firebaseapp.com',
    storageBucket: 'note-app-f7203.firebasestorage.app',
    measurementId: 'G-7P08HM1L5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0uwevy6gnt50fKHXE32zBN6l4WYMvhX0',
    appId: '1:361709866355:android:328b4b279a4dfcc09e4906',
    messagingSenderId: '361709866355',
    projectId: 'note-app-f7203',
    storageBucket: 'note-app-f7203.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwXIzyZuGKwKNDoKI2uYzmsc_crs2CCmM',
    appId: '1:361709866355:ios:1a9ddd318eea09689e4906',
    messagingSenderId: '361709866355',
    projectId: 'note-app-f7203',
    storageBucket: 'note-app-f7203.firebasestorage.app',
    iosBundleId: 'com.example.noteAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwXIzyZuGKwKNDoKI2uYzmsc_crs2CCmM',
    appId: '1:361709866355:ios:1a9ddd318eea09689e4906',
    messagingSenderId: '361709866355',
    projectId: 'note-app-f7203',
    storageBucket: 'note-app-f7203.firebasestorage.app',
    iosBundleId: 'com.example.noteAppV2',
  );
}
